import React from "react"
import { Box, Heading, Link } from "@chakra-ui/layout"
import Head from "next/head"

export default function Home() {
  return (
    <Box p="0 2rem">
      <Head>
        <title>Dedupe Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        minH="100vh"
        p="4rem 0"
        flex="1 1"
        display="flex"
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
      >
        <Heading as="h1" size="2xl">
          Welcome to{" "}
          <Link color="teal.500" href="https://nextjs.org">
            Next.js!
          </Link>
        </Heading>
      </Box>
    </Box>
  )
}
